GET localhost:8080

###

POST localhost:8080/generate
Content-Type: application/json

{ "keywords": "is an orange called orange because it is orange or is the color orange called orange because of the fruit orange" }